### ISSUE TITLE
Wrong side margins calculation

### ISSUE THREAD

**Issue by mark2b** [urbn/URBNAlert#26]
In the method [URBNAlertViewController show] pay attention to the next lines

```
    else if ([[UIScreen mainScreen] respondsToSelector:@selector(nativeBounds)]) {
        screenWidth = [UIScreen mainScreen].nativeBounds.size.width;
    }
    CGFloat sideMargins = screenWidth * 0.05;
```

**screenWidth** has real retina screen size, but **sideMargins** should be in logical points, for example for iPhone 6 screenWidth = 750 and sideMargins = 37.7 instead of ~18 points

5% screen margins is good enough, but now actually you have 10%

**Comment by ryang1428** [comment]
Good point. The initial thought when building the alert view was that when displaying on larger devices, like an iPhone 6+ or iPad, it would not be so close to the edge, so that calculation gave it an extra bit of 'padding'. That being said, I see your case where it should be consistent for all devices.

@mark2b Just curious, did you just come across this looking through the code, or when using an alert?

**Comment by mark2b** [comment]
I looked in the code where can I control side margins and found this one.

**Comment by ryang1428** [comment]
Gotcha. So optimally you would like to see some type of style options on the side margins?

**Comment by mark2b** [comment]
Not sure. Probably better to add optional property alertWith. In my case I use custom view loaded from Nib without title and message text. My client requires that alerts must be exactly as designer did.

**Comment by jgrandelli** [comment]
So @mark2b one thing we are discussing internally is adding a style option for min & max alert width. This would allow containing apps to set a per alert (or global) min and max width for alerts. This means that the alert would respect a particular margin horizontally but also only get so big on larger devices. This could also permit such things as having different sized alerts all in the same app. Think a text based alert you want kept smaller and an image based alert you want closer to full screen. How does this sounds?

**Comment by mark2b** [comment]
Sounds good, and with min == max I can control alert width

**Comment by ryang1428** [comment]
@mark2b This was pushed into master and will be in the next release (for the pod). I am going to try to get a couple of other things in v1.7 so if you would like you can point your podfile to master for now

**Comment by mark2b** [comment]
Thanks, 
There is one more issue. URBNAlertStyle doesn't copy alertMinWidth and alertMaxWidth in the copyWithZone method. As result it can not be configurable with URBNAlertController.

Thanks
