### ISSUE TITLE
Incorrect buttons margin

### ISSUE THREAD

**Issue by mark2b** [urbn/URBNAlert#27]
There is a property "buttonHorizontalMargin", but you use it for vertical margin too. There is no way to set vertical button margin. For example I need only bottom one and not top margin.

Anyway I really like this project.

**Comment by ryang1428** [comment]
I will look into this as well thanks for reporting it

**Comment by ryang1428** [comment]
@mark2b This issue, as well as the alert width issue are both addressed and released in v1.7. Thanks again for reporting them

**Comment by ryang1428** [comment]
@mark2b please see here for more info on the update: https://github.com/urbn/URBNAlert/releases/tag/1.7
