### ISSUE TITLE
URBNAlertStyle doesn't copy alertMinWidth and alertMaxWidth in the copyWithZone method

### ISSUE THREAD

**Issue by mark2b** [urbn/URBNAlert#33]
URBNAlertStyle doesn't copy alertMinWidth and alertMaxWidth in the copyWithZone method. As result it can not be configurable with URBNAlertController.

Thanks

**Comment by ryang1428** [comment]
Thats my bad-- I didn't have a getter in the .m so I completely missed that one. 

1.7.1 will be up soon with that fix

**Comment by ryang1428** [comment]
@mark2b 1.7.1 is up
