### ISSUE TITLE
Height doesn't adjust

### ISSUE THREAD

**Issue by anthonycastelli** [urbn/URBNAlert#39]
When I have a long string (roughly 6-7 lines long) the alert won't scale up height from its default size, instead, I have to scroll the UITextView. Is there something I am missing?

Also: I am running this in a Swift project.

**Comment by ryang1428** [comment]
I actually believe that I ran into this last night when I was doing something with a string with a few `\n` in it. Does your long string contain any `\n`? If so, I had planned to tackle this issue. If not, could you post an example 'long string'? Thanks.

**Comment by anthonycastelli** [comment]
It does contain line breaks in it. Didn't even cross my mind that this would cause issues.

**Comment by ryang1428** [comment]
Ok cool, I'll look into this and give you an update when I have one. Thanks for reporting.

**Comment by anthonycastelli** [comment]
Awesome, thanks!

**Comment by ryang1428** [comment]
@anthonycastelli A fix for this issue was merged and released in v1.8.1

**Comment by anthonycastelli** [comment]
Awesome. Thanks a million!!
