### ISSUE TITLE
Don't use windows.firstObject as presentingWindow

### ISSUE THREAD

**Issue by maimake** [urbn/URBNAlert#48]
In my personal app, the first window isn't the Normal Window, it's a StatusBar Window. So I don't think the first window is suitable, because status bar window should not be the key window when alert dismissed.

I suggest that use one of following window to be presentingWindow:
1.the Key Window
2.the normal window which level is the max
3.the window in AppDelegate

**Comment by ryang1428** [comment]
@maimake Thanks for the input. Question, are you testing against iOS 8 or 9? I just want to confirm that it is not related a specific iOS version

**Comment by ryang1428** [comment]
@maimake Are you doing something odd in you app that causes this? Looking into the docs a bit: 

> This property contains the UIWindow objects currently associated with the app. This list does not include windows created and managed by the system, such as the window used to display the status bar.

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/occ/instp/UIApplication/windows

That all being said, I am still going to look into using the key window
