### ISSUE TITLE
Statusbar color

### ISSUE THREAD

**Issue by ghost** [urbn/URBNAlert#51]
my application statusbar is white, after popup alert my statusbar color turn to black color  after close turn to white. how can i disable to turn to black. thank you

**Comment by ryang1428** [comment]
@kakkuk Thank you for reporting this issue. I have not seen this happen, and I could not get it to happen. Do you have any more info? Are you manually modifying your status bar in any way or anything like that?

**Comment by ryang1428** [comment]
I was able to replicate this issue. Looking into it.

**Comment by snailjj** [comment]
where？

**Comment by ryang1428** [comment]
@kakkuk @1791422018 Fix is currently in a PR: https://github.com/urbn/URBNAlert/pull/56. It should get merged in the next day or so

**Comment by ryang1428** [comment]
@kakkuk @1791422018 URBNAlert v1.9.1 was just pushed to trunk which fixes this issue. Thanks for reporting.
