### ISSUE TITLE
What I can do make Status bar become Black????

### ISSUE THREAD

**Issue by snailjj** [urbn/URBNAlert#54]
I have a project.when status bar is white is so unpretty  I want to change Status bar become black? What I can do.

**Comment by ryang1428** [comment]
@1791422018 Thanks for reporting the issue. Do you have any more info? I attempted, but cannot reproduce your issue. How are you setting your status bar color/style?

**Comment by ryang1428** [comment]
I believe this is related to issue #51. I was able to reproduce, and am looking into it.
