### ISSUE TITLE
New Demo

### ISSUE THREAD

**Issue by ryang1428** [urbn/URBNAlert#55]
The demo could use a nice refresh with some better (and prettier) examples

**Comment by wdcurry** [comment]
An FYI.. the demo does not run on my setup, which is generally up-to-date. It builds fine, but never actually runs.
{edit: as delivered, the schema required to run the app was not set. Once reset, it runs..  cheers!}

**Comment by ryang1428** [comment]
Did you ensure you are selecting `URBNAlert-Example` as your active scheme? I have the example up right now on a iOS 9.2 sim in Xcode 7.2
