### ISSUE TITLE
display of separator between buttons: how?

### ISSUE THREAD

**Issue by wdcurry** [urbn/URBNAlert#57]
I have set both separatorHeight and separatorColor but see no separator, and yes, i have ensure the alert background color is different ;) ..

Thanks for any tips..

**Comment by ryang1428** [comment]
I assume you are using the vertical button layout with 2+ buttons? If so, you should see the separators when doing the following:

```
    uac.alertStyler.separatorHeight = @1;
    uac.alertStyler.separatorColor = [UIColor darkGrayColor];
```

**Comment by wdcurry** [comment]
yes.. 2 buttons, and i have tried various combinations, including the above, to no avail. I will try adjusting the demo to achieve the desired result next.

**Comment by wdcurry** [comment]
The above code has no impact on the two-button example in the demo. No errors/no warnings/no separator.

I am simply trying to produce an alert view with the same new styling of UIAlertView PLUS the ability to render justified message text. I can perhaps use the no-separator look, but would prefer not to. The right-justification was greatly requested by my QA folks, thus looking into this repo.

**Comment by ryang1428** [comment]
@wdcurry Is this along the lines of what you are trying to do?

```
    URBNAlertViewController *uac = [[URBNAlertViewController alloc] initWithTitle:@"Multiple Buttons" message:@"When 3 or more buttons are added to the alert, they then align in a vertical layout."];

    uac.alertStyler.separatorHeight = @2;
    uac.alertStyler.separatorColor = [UIColor purpleColor];
    uac.alertStyler.useVerticalLayoutForTwoButtons = @YES;
    uac.alertStyler.messageAlignment = NSTextAlignmentRight;

    [uac addAction:[URBNAlertAction actionWithTitle:@"Submit" actionType:URBNAlertActionTypeNormal dismissOnActionComplete:NO actionCompleted:^(URBNAlertAction *action) {
        // Alternate way to dismiss the currently active alert
        [[URBNAlertController sharedInstance] dismissAlert];
    }]];

    [uac addAction:[URBNAlertAction actionWithTitle:@"Button Two" actionType:URBNAlertActionTypeDestructive actionCompleted:^(URBNAlertAction *action) {
        // Do something
    }]];

    [uac show];
```

![Example Of Code Above](http://f.cl.ly/items/0d0a2L0A0d1s0g3b3p3J/Screen%20Shot%202015-12-21%20at%208.30.30%20AM.png)
