### ISSUE TITLE
Issue with activateConstraints on iOS 7

### ISSUE THREAD

**Issue by oberlaender** [urbn/URBNAlert#72]
in the version v1.9.7 `activateConstraints` is used which only available since **iOS 8**

**Comment by jgrandelli** [comment]
@oberlaender the pod spec specifies support for >= iOS 8.0. This pod has not be tested or verified in any way against iOS 7. `activateConstraints` may not be the only thing that doesn't work so well when used on iOS 7.

**Comment by jgrandelli** [comment]
Actually @oberlaender, @ndis1 just pointed out that you were talking about a version that did in fact support iOS 7. My bad. I just pushed up a fix https://github.com/urbn/URBNAlert/pull/74. I'll have a release out soon for you.

**Comment by jgrandelli** [comment]
Fixed in #74
