### ISSUE TITLE
Convert to Swift

### ISSUE THREAD

**Issue by jgrandelli** [urbn/URBNAlert#73]
Convert pod to Swift. Maybe also consider the use of stack views.

**Comment by KVTaniguchi** [comment]
from inside this pod or make a new repo?

**Comment by jgrandelli** [comment]
Thats a great question @KVTaniguchi not sure to be honest. We'll have to figure out whether or not we want to maintain the ability to iterate on the old version. My initial thought is to build a completely Swift 3 version of this right here in this pod and then increment a full version number (3.0). @ryang1428 thoughts?

**Comment by ryang1428** [comment]
I would be down for v3.0 being the Swift release

**Comment by MobileMon** [comment]
This website will convert Objective C to Swift

https://objectivec2swift.com/#/home

Works quite nice, I've used it myself!

**Comment by ryang1428** [comment]
v3.0 was re-written in Swift !
