### ISSUE TITLE
Support Rotation

### ISSUE THREAD

**Issue by codecaffeine** [urbn/URBNAlert#8]
When I present an alert and then rotate my device… the alert view rotates correctly, but the blur area doesn’t.

![screen shot 2015-04-03 at 2 58 01 pm](https://cloud.githubusercontent.com/assets/71474/6987111/0de5060c-da12-11e4-8cfc-bc9a40404573.png)

**Comment by ryang1428** [comment]
if you have any suggestions on this, please let me know. I attempted to get a new screenshot on rotation but the animation is super jumpy and ugly

**Comment by flippinjoe** [comment]
So, is there any reason you're doing your own blurring logic instead of using the UIVisualEffectView?

**Comment by codecaffeine** [comment]
So I played replacing the blur logic with UIVisualEffectView and while it’s an easy fix, it’s not as nice visually. It’s super blurry and the only style options you have are ExtraLight, Light, and Dark. It also requires iOS 8 and we’re supporting this pod back to iOS 7.

**Comment by ryang1428** [comment]
some info on this matter in here: http://www.raywenderlich.com/84043/ios-8-visual-effects-tutorial

i tried implementing `willTransitionToSize` and `animateAlongsideTransition` and it still is pretty choppy. Although, if I pass YES to afterScreenUpdates when taking a screenshot it delays the rotation but doesn't look choppy when rotating
